language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php:
        - 7.1
        - hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
  - vendor/bin/phpunit
